---
- name: Backup Cisco Nexus Devices
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: nxos
    device_type: cisco_nxos

  tasks:
    - name: Get current timestamp
      set_fact:
        backup_time: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

    - name: Get running configuration
      cisco.nxos.nxos_command:
        commands: show running-config
      register: config_output
      tags: backup

    - name: Save running configuration to file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "/home/semaphore/{{ inventory_hostname }}_{{ backup_time }}.txt"
      delegate_to: localhost
      run_once: false
      tags: backup
