---
- name: Backup Cisco Switch Configuration
  hosts: all  # Or target specific hosts from your inventory
  gather_facts: false  # Disable fact gathering for faster execution

  vars:
    ansible_network_os: ios
    device_type: cisco_ios
    
  tasks:
    - name: Get running configuration
      cisco.ios.ios_config:
        intended_config: running
        match: line
        diff_against: intended
      register: config_output
      tags: backup

    - name: Save running configuration to a file
      copy:
        content: "{{ config_output.running_config }}"
        dest: "/tmp/semaphore/backups/{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
      tags: backup
