---
- name: Gather Cisco IOS Interface IP
  hosts: switches
  gather_facts: no
  connection: network_cli
  
  vars:
    ansible_network_os: ios
    device_type: cisco_ios
  
  tasks:
    - name: Run cli_command on Cisco IOS and display results
      cisco.ios.ios_command:
        commands:
          - show ip int br
      register: int_output

    - name: Display the output
      debug:
        var: int_output.stdout_lines
