---
- name: Get Cisco NXOS device facts
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: nxos
    device_type: cisco_nxos
    
  tasks:
    - name: Collect NXOS facts
      cisco.nxos.nxos_facts:
        gather_subset:
          - all
      register: device_info

    - name: Display model and serial number
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model: {{ device_info.ansible_facts.ansible_net_model }}
          Software: {{ device_info.ansible_facts.ansible_net_version }}
          Serial Number: {{ device_info.ansible_facts.ansible_net_serialnum }}
