---
- name: Configure Cisco IOS Device
  hosts: all  # Replace with your inventory group name
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios
    device_type: cisco_ios

  tasks:
    - name: Initial Configuration
      cisco.ios.ios_config:
        lines:
          - "service password-encryption"
          - "no ip http server"
          - "no ip http secure-server"
          - "ip http authentication local"
          - "snmp-server view viewer iso included"
          - "snmp-server group grp1 v3 priv read ascview write ascview notify viewer"
          - "snmp-server user admin GRP1 v3 auth sha authadmin priv aes 128 privadmin"
          - "snmp-server host 10.50.40.6 version 3 priv admin"
          - "snmp-server enable traps"
          
          - "ntp server 10.1.1.9"
          - "ntp server 10.1.1.10"
      tags: basic config
