---
- name: Gather Cisco IOS Device Information
  hosts: hq_switches
  gather_facts: no
  connection: network_cli
  
  vars:
    ansible_network_os: ios
    device_type: cisco_ios
  
  tasks:
    - name: Gather device facts
      cisco.ios.ios_facts:
        gather_subset:
          - all
      register: device_facts

    - name: Get show version output
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

#    - name: Get hostname
#      cisco.ios.ios_command:
#        commands:
#          - show running-config | include hostname
#      register: hostname_output

    - name: Get uptime information
      cisco.ios.ios_command:
        commands:
          - show version | include uptime
      register: uptime_output

    - name: Get running configuration summary
      cisco.ios.ios_command:
        commands:
          - show running-config | include (interface|ip|router)
      register: config_summary

    - name: Display device information
      debug:
        msg: |
          ===============================================
          Device: {{ inventory_hostname }}
          IP Address: {{ ansible_host }}
          Device Type: {{ device_type | default('Unknown') }}
          Site: {{ site | default('Unknown') }}
          ===============================================
          
#          HOSTNAME:
#          {{ hostname_output.stdout[0] }}
          
          UPTIME:
          {{ uptime_output.stdout[0] }}
          
          VERSION INFO:
          Software: {{ device_facts.ansible_facts.ansible_net_version }}
          Model: {{ device_facts.ansible_facts.ansible_net_model }}
          Serial: {{ device_facts.ansible_facts.ansible_net_serialnum }}
          Image: {{ device_facts.ansible_facts.ansible_net_image }}
          
          MEMORY INFO:
          Total Memory: {{ device_facts.ansible_facts.ansible_net_memtotal_mb }} MB
          Free Memory: {{ device_facts.ansible_facts.ansible_net_memfree_mb }} MB
          
          ===============================================
