---
- name: Configure Cisco IOS Device
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    #ntp_server: "10.50.1.211"
    ansible_network_os: ios
    device_type: cisco_ios

  tasks:
    - name: Configure NTP server
      cisco.ios.ios_config:
        lines:
          - "ntp server {{ ntp_server }}"
      tags: ntp
