- name: Gather Cisco IOS Version Information
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Execute show version command
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Display the output
      debug:
        var: version_output.stdout_lines
