---
- name: Get Cisco IOS device facts
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    device_type: cisco_ios
    export_path: "/home/semaphore"
    
  tasks:
    - name: Collect IOS facts
      cisco.ios.ios_facts:
        gather_subset:
          - all
      register: device_info

    - name: Display model and serial number
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model: {{ device_info.ansible_facts.ansible_net_model }}
          Software: {{ device_info.ansible_facts.ansible_net_version }}
          Serial Number: {{ device_info.ansible_facts.ansible_net_serialnum }}

    - name: Create export directory if it doesn't exist
      file:
        path: "{{ export_path }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Export device information to CSV file
      lineinfile:
        path: "{{ export_path }}/cisco_device_inventory.csv"
        line: "{{ inventory_hostname }},{{ device_info.ansible_facts.ansible_net_model }},{{ device_info.ansible_facts.ansible_net_version }},{{ device_info.ansible_facts.ansible_net_serialnum }}"
        create: yes
        mode: '0644'
      delegate_to: localhost

    - name: Create CSV header (run once)
      lineinfile:
        path: "{{ export_path }}/cisco_device_inventory.csv"
        line: "Hostname,Model,Software Version,Serial Number"
        insertbefore: BOF
        create: yes
        mode: '0644'
      delegate_to: localhost
      run_once: true
