---
- name: Gather Cisco IOS Interface IP
  hosts: all
  gather_facts: no
  connection: network_cli
  
  vars:
    ansible_network_os: ios
    device_type: cisco_ios

  tasks:
    - name: Run cli_command on Cisco IOS and display results
      block:
      - name: Run cli_command on Cisco IOS
        ansible.netcommon.cli_command:
          command: show ip int br
        register: result

      - name: Display result to terminal window
        debug:
          var: result.stdout_lines
      when: ansible_network_os == 'cisco.ios.ios'
