---
- name: Get Cisco IOS device facts
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    device_type: cisco_ios
    
  tasks:
    - name: Collect IOS facts
      cisco.ios.ios_facts:
        gather_subset:
          - all
      register: device_info

    - name: Display model and serial number
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model: {{ device_info.ansible_facts.ansible_net_model }}
          Serial Number: {{ device_info.ansible_facts.ansible_net_serialnum }}
