---
- name: Get Cisco IOS device facts
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    device_type: cisco_ios
    export_path: "/home/semaphore"
    
  tasks:
    - name: Collect IOS facts
      cisco.ios.ios_facts:
        gather_subset:
          - all
      register: device_info

    - name: Display model and serial number
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model: {{ device_info.ansible_facts.ansible_net_model }}
          Software: {{ device_info.ansible_facts.ansible_net_version }}
          Serial Number: {{ device_info.ansible_facts.ansible_net_serialnum }}

    - name: Export detailed device information to JSON file
      copy:
        content: |
          {
            "hostname": "{{ inventory_hostname }}",
            "model": "{{ device_info.ansible_facts.ansible_net_model }}",
            "software_version": "{{ device_info.ansible_facts.ansible_net_version }}",
            "serial_number": "{{ device_info.ansible_facts.ansible_net_serialnum }}",
          }
        dest: "{{ export_path }}/{{ inventory_hostname }}_device_info.json"
        mode: '0644'
      delegate_to: localhost
