---
- name: Manage NetBox objects
  hosts: localhost
  gather_facts: false
  collections:
    - netbox.netbox

  tasks:
    - name: Create Site
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "New York Site"
          slug: "new-york"
        state: present
        validate_certs: "{{ validate_certs }}"

    - name: Create Device Role
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "Firewall"
          slug: "firewall"
          color: "ff0000"
        state: present
        validate_certs: "{{ validate_certs }}"
