---
- name: Get all NetBox sites
  hosts: all
  gather_facts: false
  vars:
    netbox_url: http://10.50.40.7:8000
    netbox_token: 1eed18a2573048c183a2acddf49e9f3494a594d8
    validate_certs: false

  tasks:
    - name: Query all sites from NetBox
      uri:
        url: "{{ netbox_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        return_content: yes
        validate_certs: no
      register: netbox_sites

    - name: Show site info
      debug:
        msg: "{{ item.name }} (Slug: {{ item.slug }})"
      loop: "{{ (netbox_sites.json.results | default([])) }}"
