---
- name: Get all NetBox sites
  hosts: all
  gather_facts: false
  vars:
    netbox_url: http://10.50.40.7:8000/api/dcim/sites/
    netbox_token: 1eed18a2573048c183a2acddf49e9f3494a594d8
    validate_certs: false
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Query all sites from NetBox
      uri:
        url: "{{ netbox_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        return_content: yes
        validate_certs: no
      register: netbox_sites

    - name: Display NetBox site details in readable format
      debug:
        msg: |
          Site Name: {{ item.name }}
          Site_ID     : {{ item.SITE_ID }}
          Slug     : {{ item.slug }}
          Status   : {{ item.status.label if item.status is defined and item.status.label is defined else 'N/A' }}
      loop: "{{ netbox_sites.json.results }}"
