- hosts: all
  gather_facts: false
  connection: network_cli #ansible.netcommon.network_cli

  tasks:
    - name: Run cli_command on Cisco IOS and display results
      cisco.ios.ios_ping:
        dest: 10.50.1.4
