---
- name: Gather Cisco IOS Device Information
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli
  
  vars:
    output_dir: "./device_reports"
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
