---
   
- name: Additional Network Diagnostics
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli
  
  vars:
    output_dir: "./device_reports"
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
  
  tasks:
    - name: Check device connectivity and response time
      cisco.ios.ios_ping:
        dest: 10.50.1.254
        count: 3
      register: ping_result
      ignore_errors: yes

    #- name: Get routing table
      #cisco.ios.ios_command:
        #commands:
          #- show ip route summary
      #register: route_summary
      #ignore_errors: yes

    - name: Get VLAN information (for switches)
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_info
      ignore_errors: yes
      when: device_role == "switch"

    - name: Display connectivity status
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Ping to 8.8.8.8: {{ 'SUCCESS' if ping_result.packets_tx == ping_result.packets_rx else 'FAILED' }}
          {% if ping_result.packets_tx == ping_result.packets_rx %}
          Packet Loss: 0%
          {% else %}
          Packet Loss: {{ ((ping_result.packets_tx - ping_result.packets_rx) / ping_result.packets_tx * 100) | round(2) }}%
          {% endif %}
      when: ping_result is defined
