---
   
- name: Additional Network Diagnostics
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli
  
  vars:
    output_dir: "./device_reports"
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
    ansible_network_os: ios
    device_type: cisco_ios
  
  tasks:
    - name: Check device connectivity and response time
      cisco.ios.ios_ping:
        dest: 10.50.1.254
        count: 3
      register: ping_result
      ignore_errors: yes
